The primary purpose of our program is to create a game of five-in-a-row chess that provides individuals one more choice of relaxing to play chess with computer, so that they could have fun even if they do not have a partner. This will be achieved through the use of computer auto move.

Our program's functionality includes the ability to detect a player's move on the chessboard and respond with a computer move to determine the game's progress if one of the player has achieved the winning criterion of victory, five in a row. Additionally, our program enables users to change game modes and players, providing a versatile and engaging chess experience.

Our program takes user input through left-clicks on various buttons and coordinates of the chessboard interface we have created. The program's output includes the chess piece`s image displayed upon clicking, a win or lose message, mode changes initiated through mode selection buttons, and the game's restart or end through dedicated buttons.

In [1]:
    def __init__(self, keyList):
        # Self.board is the 2d list that is used to store the state of the game.
        # It is being initialized as a boardSize x boarSize 2d list with zeros as initial values.
        self.board = [[0 for i in range(boardSize)] for j in range(boardSize)]
        # It stores the parameter keyList to self.keyList. keyList is a list that contains [1,2].
        # 1 represent the key that player 1 has, and 2 represents the key that player 2 has. You can think of 1 and 2 as
        # X and O in tic-tac-toe
        self.keyList = keyList
        # Initialize winner as none
        self.winner = None

In [2]:
    def place_key(self, x, y, key):
        # A setter method that changes board[x][y] to key(1 or 2)
        # For example when player makes the move at the center of a 9x9 board, it will pass in parameters 4 as x, 4 as y and 1 as key.
        # Then self.board[4][4] will become 1.
        self.board[x][y] = key

self.board

The data contained in the 2D list was used to store and represent the status of the full chessboard of all coordinates, using 0,1,2, which represent empty, black chess and white chess respectively. This list will then be updated when any time a computer or human player has entered a new chess on the chessboard.

Using a two-dimensional list to store the status of the given chessboard coordinate provides a more convenient way to access each point and allows for the determination of the game's status in one loop. Otherwise, the status of each coordinate would be written in a separate list, making it difficult to iterate through and determine the winner. Additionally, using a list allows for mapping of the mouse's x and y coordinates to the corresponding element in the list, making it easier to change the board's state when placing a piece. This feature also facilitates the process of checking for five in a row horizontally, vertically, or diagonally. Therefore, using a list simplifies the game's implementation and ease the overall difficulty by using different variables, which would make the list self-adapt to different board size for future modification.

In [3]:
 # A method that checks whether the state reached endgame.
    # Return the player key if it wins, return -1 if draws, and return 0 if not at endgame
    def check_status(self, state):
        state = arr = np.array(state, dtype = int)
        # Appends all dimensions of the board into checkList.
        checkList = []
        # A boolean representing draw or not

        if len(self.get_empty(state)) == 0:
            # Return -1 if draws
            return -1

        # Diags only contributes to endgame if the length of it is larger than 5, therefore i begins from where len(diags) is 5,
        # And ends at len(diags) is 5. diags less than 5 are not considered the considered amount of diags would be same as
        # The boardSize, which another loop variable index starts at 0 and +=1 each time would get all rows and columns

        # A loop variable used to represent index of rows and columns
        index = 0

        for i in range(-boardSize + winCount, winCount):
            # append rows
            # The state[i :] means the ith row's elements of the board.
            # For example, state[0 :] is a 1d list representing the first row of the board.
            checkList.append(state[i, :].tolist())
            # The state[: i] means the ith row's elements of the board.
            # For example, state[: 0] is a 1d list representing the first column of the board.
            # Append columns
            checkList.append(state[:, i].tolist())
            # Updates the loop variable
            index += 1

            # Append diags
            checkList.append(state.diagonal(i).tolist())
            # Append the other side diags
            checkList.append(state[::-1].diagonal(i).tolist())

        # Aata type int to string
        checkList = [''.join(np.char.mod('%d', checkList[i])) for i in range(len(checkList))]

        # Iterate through checkList to check if 5 1s or 2s are connected
        for i in range(len(checkList)):
            if str(self.keyList[0]) * winCount in checkList[i]:
                # Print the winner for debugging
                print('human player win')
                # Return 1 representing p1 wins
                return self.keyList[0]

            elif str(self.keyList[1]) * winCount in checkList[i]:
                # Print the winner for debugging
                print('ai player win')
                # Return 2 representing p2 wins
                return self.keyList[1]

        # Return 0 if game should continue
        return 0

IndentationError: unexpected indent (1039225371.py, line 3)

In [ ]:
while active == 0:
    if players[currentPlayer].move():
        currentPlayer = abs(currentPlayer - 1)

    active = myBoard.check_status(myBoard.get_board())
    tv.update_idletasks()
    tv.update()

This check_status(self,state) procedure will receive a parameter of chessboard list containing integers of each points on the chessboard represented by 0,1,2 as empty, white, black, respectively, called 'state'. It then determines if the game ends or draws or continues and return different values for those different states. This procedure contributes to the game by detecting whether the game is ending or continue.

This code defines a method named `check_status` that takes in a two-dimensional list `state` representing the current state of a five-in-a-row game. The method first initializes an empty list `checkList` and determines whether the game is over by checking if there are any empty spaces left on the board. Then, it uses a loop to iterate over all possible winning combinations, including rows, columns, and diagonals. The method appends these winning combinations to `checkList`. The winning combinations are then converted to strings using a list comprehension. Finally, the method checks if either player has won the game by searching for a substring of consecutive identical symbols (`X` or `O`, represented by `self.keyList[0]` and `self.keyList[1]`, respectively) of length `winCount` in each string in `checkList`. If a winning combination is found, the method prints the winner and the winning line, and returns the winner's symbol. If no winner is found but the board is full, the method returns `-1`. Otherwise, it returns `0`.

The first call to the procedure will be user clicking on the chessboard and made a change of the chessboard from an empty chessboard, and the 'state' value of the board, integer board list of [[2 2 2 2 2 0 0 0 1]，
                                    [0 0 0 0 1 0 0 0 0]，
                                    [0 0 0 0 0 0 0 0 0]，
                                    [0 0 0 0 0 0 0 0 0]，
                                    [1 0 0 0 1 0 0 0 0]，
                                    [0 0 0 0 0 0 0 0 0]，
                                    [0 0 0 0 0 0 0 0 0]，
                                    [0 0 0 0 0 0 0 0 0]，
                                    [1 0 0 0 2 0 2 1 1]]will be transferred in to this procedure.

The second call to the procedure will be the computer player placing the last chess at the last possible place on the chess board, and the status of the board in 'state' "[ [1,2,1,2,2,2,1,2,1],
                [2,2,1,2,1,2,1,2,1],
                [1,1,2,2,1,2,1,1,2],
                [1,2,1,1,2,1,2,1,1],
                [1,2,1,2,1,2,1,2,1],
                [2,2,2,1,1,2,1,2,1],
                [1,1,1,2,1,2,1,2,2],
                [2,2,2,1,2,1,1,1,1],
                [1,2,1,2,2,1,2,2,2] ] will be transferred in to this procedure.

The first call to the procedure will first test if the chessboard is full, which in this case is not full. Then it will test if the human player has won the game by adding the human player`s chess list to it, and in this case human player is not winning. Then this procedure will test if the computer has won by adding the computer list to check with the 'checklist[]', and in this case it is winning.

The second call to the procedure will only test if the chessboard is full, in this case it is winning the game.

The result of the first call to the procedure will be returning the dialogue of 'ai player win', and stop the program by returning the list of computer player`s chess.

The result of the second call to the procedure will be returning -1 to the overall function of the game, and the game will stop because it is being considered a draw to the game.